// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_md
arma::mat compute_md(arma::mat x);
RcppExport SEXP _anomalyDetection_compute_md(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_md(x));
    return rcpp_result_gen;
END_RCPP
}
// compute_bd
arma::mat compute_bd(arma::mat x, bool normalize);
RcppExport SEXP _anomalyDetection_compute_bd(SEXP xSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_bd(x, normalize));
    return rcpp_result_gen;
END_RCPP
}
// compute_md_and_bd
arma::mat compute_md_and_bd(arma::mat x, bool normalize);
RcppExport SEXP _anomalyDetection_compute_md_and_bd(SEXP xSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_md_and_bd(x, normalize));
    return rcpp_result_gen;
END_RCPP
}
// compute_hc
arma::mat compute_hc(int n, int p, int nsim);
RcppExport SEXP _anomalyDetection_compute_hc(SEXP nSEXP, SEXP pSEXP, SEXP nsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hc(n, p, nsim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_anomalyDetection_compute_md", (DL_FUNC) &_anomalyDetection_compute_md, 1},
    {"_anomalyDetection_compute_bd", (DL_FUNC) &_anomalyDetection_compute_bd, 2},
    {"_anomalyDetection_compute_md_and_bd", (DL_FUNC) &_anomalyDetection_compute_md_and_bd, 2},
    {"_anomalyDetection_compute_hc", (DL_FUNC) &_anomalyDetection_compute_hc, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_anomalyDetection(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
