# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_md <- function(x) {
    .Call('anomalyDetection_compute_md', PACKAGE = 'anomalyDetection', x)
}

compute_bd <- function(x, normalize) {
    .Call('anomalyDetection_compute_bd', PACKAGE = 'anomalyDetection', x, normalize)
}

compute_md_and_bd <- function(x, normalize) {
    .Call('anomalyDetection_compute_md_and_bd', PACKAGE = 'anomalyDetection', x, normalize)
}

compute_hc <- function(n, p, nsim) {
    .Call('anomalyDetection_compute_hc', PACKAGE = 'anomalyDetection', n, p, nsim)
}

